/* generated by gendata.sno */

extern const char CF_FMT[];		/* FORMAT */
extern const char DP_FT3[];		/* FORMAT */
extern const char DP_FT1[];		/* FORMAT */
extern const char DP_FT2[];		/* FORMAT */
extern const char EM_FMT1[];		/* FORMAT */
extern const char EM_FMT2[];		/* FORMAT */
extern const char EM_FMT3[];		/* FORMAT */
extern const char IN_FT1[];		/* FORMAT */
extern const char NR_FMT1[];		/* FORMAT */
extern const char NR_FMT2[];		/* FORMAT */
extern const char WA_FMT[];		/* FORMAT */
extern const char ALOCFL[];		/* FORMAT */
extern const char ARTHNO[];		/* FORMAT */
extern const char CMTIME[];		/* FORMAT */
extern const char EJECTF[];		/* FORMAT */
extern const char ERRCF[];		/* FORMAT */
extern const char EXNO[];		/* FORMAT */
extern const char FTLCF[];		/* FORMAT */
extern const char GCFMT[];		/* FORMAT */
extern const char INCGCF[];		/* FORMAT */
extern const char INTIME[];		/* FORMAT */
extern const char KSTSF[];		/* FORMAT */
extern const char LASTSF[];		/* FORMAT */
extern const char NODMPF[];		/* FORMAT */
extern const char NRMEND[];		/* FORMAT */
extern const char NVARF[];		/* FORMAT */
extern const char PKEYF[];		/* FORMAT */
extern const char PRTOVF[];		/* FORMAT */
extern const char READNO[];		/* FORMAT */
extern const char SCANNO[];		/* FORMAT */
extern const char SOURCF[];		/* FORMAT */
extern const char STATHD[];		/* FORMAT */
extern const char STDMP[];		/* FORMAT */
extern const char STGENO[];		/* FORMAT */
extern const char STGETM[];		/* FORMAT */
extern const char SUCCF[];		/* FORMAT */
extern const char SYSCMT[];		/* FORMAT */
extern const char TIMEPS[];		/* FORMAT */
extern const char TITLEF[];		/* FORMAT */
extern const char TITLEF1[];		/* FORMAT */
extern const char WRITNO[];		/* FORMAT */
# ifndef NO_STATIC_VARS
extern struct res res;
# endif
