#!/bin/sh
# $Id: check,v 1.2 2013/08/14 21:31:47 phil Exp $
# Test a combination of include/code/libs ~sigh~
# Phil Budne
# January 2, 2012

# XXX options to enable output, run program?

## ACK! accept options in any order?
while [ "x$1" ]; do
    case "$1" in
    -r) RUN=1; shift;;
    -d) DEBUG_CHECK=1; set -x; shift;;
    -*) echo bad option $1; exit 1;;
    *) break;;
    esac
done

INCLUDES="$1"
BODY="$2"
LIBS="$3"

TMP=/tmp/check$$
TMP_C=${TMP}.c
trap "rm -f $TMP $TMP_C" 0

rm -f $TMP $TMP_C
for I in $INCLUDES; do
    echo "#include <$I>" >> $TMP_C
done
echo "int main(int argc, char *argv[]) {" >> $TMP_C
echo "    $BODY;"	>> $TMP_C
echo "    return 0;"	>> $TMP_C
echo "}"		>> $TMP_C

test "$DEBUG_CHECK" && cat $TMP_C

if ${CC:-cc} $CFLAGS -o $TMP $TMP_C $LIBS >/dev/null 2>&1; then
    if [ "$RUN" ]; then
	$TMP
	exit $?
    else
	exit 0
    fi
else
    exit 1
fi
