# $Id: Makefile.netbsd,v 1.3 2005/12/07 14:19:27 phil Exp $

DISTNAME=	snobol4-1.1
CATEGORIES=	lang
MASTER_SITES=	ftp://ftp.snobol4.org/snobol/

MAINTAINER=	phil@ultimate.com

HAS_CONFIGURE=	yes
CONFIGURE_SCRIPT=configure
CONFIGURE_ENV+=	PREFIX=${PREFIX}
CONFIGURE_ARGS+=--prefix=${PREFIX}

.include "../../mk/bsd.pkg.mk"
