@clear
@echo ---Snobol4 Regression Test---
@call nttest 100func
@call nttest 8bit
@call nttest a
@call nttest alph
@call nttest alt1
@call nttest alt2
@call nttest any
@call nttest bal
@call nttest breakx
@call nttest case1
@call nttest case2
@call nttest cat
@call nttest char
@call nttest collect
@call nttest comment
@call nttest contin
@call nttest conv2
@call nttest convert
@call nttest dump
@call nttest end
@call nttest err
@call nttest fact
@call nttest float
@call nttest ftrace
@call nttest fun1
@call nttest fun2
@call nttest hello
@call nttest ind
@call nttest intval
@call nttest len
@call nttest lexcmp
@call nttest lgt
@call nttest line
@call nttest local
@call nttest longline
@call nttest longrec
@call nttest loop
@call nttest match
@call nttest match2
@call nttest match3
@call nttest match4
@call nttest matchloop
@call nttest noexec
@call nttest openi
@call nttest openo
@call nttest openo2
@call nttest ops
@call nttest pad
@call nttest pow
@call nttest punch
@call nttest repl
@call nttest reverse
@call nttest rewind1
@call nttest roman
@call nttest space
@call nttest space2
@call nttest spit
@call nttest str
@call nttest substr
@call nttest tab
@call nttest trace1
@call nttest trace2
@call nttest trim0
@call nttest trim1
@call nttest uneval
@call nttest uneval2
@call nttest update
@call nttest words
@call nttest words1
