# MS-DOS (Intel DOS Extender) or OS/2 version.
# Remove all the ".exe" strings for Unix version.

snocone.exe:	snocone.sno snocone.sc
#
# Use "snocone in snobol4" to compile "snocone in snocone" to sc.spt
	spitbol -b snocone.sno <snocone.sc >sc.spt
#
# Run sc.spt to produce snocone.exe, which we rename sc.exe.
	spitbol -b sc.spt
	move snocone.exe sc.exe
#
# Recompile "snocone in snocone" using the first version of snocone,
# to produce snocone.spt.
	sc.exe snocone.sc
	del sc.exe
#
# Compile snocone.spt to produce 2nd version of snocone to snocone.exe,
# which we rename xx.exe.
	spitbol -b snocone.spt
	move snocone.exe xx.exe
#
# Now run xx.exe to perform all initialization and generate the
# final form of snocone, snocone.exe.
	xx.exe
	del xx.exe

test:	sc.spt
	spitbol -b sc.spt
	move snocone.exe sc.exe
	sc.exe snocone.sc
	del sc.exe
	spitbol -b snocone.spt
	move snocone.exe xx.exe
	xx.exe
	move snocone.exe yy.exe
	yy.exe snocone.sc
	spitbol -b snocone.spt
	fc /b snocone.exe xx.exe

clean:
	del sc.spt
	del sc.exe
	del snocone.spt
	del xx.exe
	del yy.exe
