# Snobol3 

CC = gcc -std=c89
FLAGS = -s -O
DEBUG = -g

all:
	$(CC) sno?.c

debug:
	$(CC) $(DEBUG) sno?.c

run:
	$(CC) $(FLAGS) sno?.c

# notes:
# compiling with c89, as close to k&r gcc gets

# flags:
# -s = linker option
# -O = optimizer option
